#include <stdio.h>
#include <malloc.h>

//function prototypes
void merge(int *, int, int);
void mergesort(int *, int, int, int);

int	//main function
main(void) {
	int len;
	int i;

	//Input your numbers needed to be sorted
	printf("How many numbers you want to sort: ");
	scanf("%d", &len);
	//declare a dynamic array to store the numbers need to sort
	int * arr = (int *)malloc(sizeof(int) * len);
	printf("Please input your numbers separated with a space: ");
	for (i = 0; i < len; ++i) {
		scanf("%d", arr + i);
	}
	//merge function which will sort a array of numbers
	merge(arr, 0, len-1);

	//print the sorted array of numbers
	for (i = 0; i < len; ++i) {
		printf("%d ", *(arr + i));
	}
	//free the heap memory
	free(arr);

	return 0 ;
}

void	//merge function, basically, what this function does is dividing a array 
	//into two parts and sorting each parts separately and then merging each part together
merge(int * sortarr, int left, int right) {
	int mid = (left + right) / 2;
	if (left < right) {
		merge(sortarr, left, mid);
		merge(sortarr, mid + 1, right);
		mergesort(sortarr, left, mid, right);
	}
}

void	//sort the two parts generated by the merge function 
mergesort(int * sortarr, int left, int mid, int right) {
	int len = right - left + 1;
	int li = left;
	int ri = mid + 1;
	int i = 0;
       //declare a temporary array to store the will-be-sorted array
	int * temarr = (int *)malloc(sizeof(int) * len);
	while (li <= mid && ri <= right) {
		if (sortarr[li] < sortarr[ri])
			temarr[i++] = sortarr[li++];
		else
			temarr[i++] = sortarr[ri++];
	}
	while (li <= mid) temarr[i++] = sortarr[li++];
	while (ri <= right) temarr[i++] = sortarr[ri++];
	//put the sorted array back to the original array
	for (i = 0; i < len; i++) 
		sortarr[left++] = temarr[i];	// This is where I take a mistake!!!!
	//free the memory mallocated by the temporary array
	free(temarr);
}
